#ifndef GUARD_CONSTANTS_THREE_HORIZONS_H
#define GUARD_CONSTANTS_THREE_HORIZONS_H

// TH-only replacements for unreachable Hoenn trainers; save flag capacity is unchanged.

// Audited unused Emerald event slots; no save-block layout changes.
#define VAR_TH_STAGE           0x40F7
#define VAR_TH_FIRST_PARTNER   0x40F8
#define VAR_TH_RIVAL_PARTNER   0x40F9
#define VAR_TH_SUPPLY_MASK     0x40FA
#define VAR_TH_SIGHTING_SEEN   0x40FB
#define VAR_TH_OUTFIT          0x40FC
#define VAR_TH_EXP_RATE        0x40FD
#define VAR_TH_AUTO_RUN        0x40FE
#define VAR_TH_FOLLOWER_OFF    0x40FF
#define VAR_TH_RIVAL_NAME_0    0x404E
#define VAR_TH_RIVAL_NAME_1    0x4083
#define VAR_TH_RIVAL_NAME_2    0x408B
#define VAR_TH_RIVAL_NAME_3    0x4091
#define VAR_TH_TRAINING_KIT_MASK 0x409B

// Playtest 9: audited unused event slots; no save layout changes.
#define VAR_TH_BROCK_GIFT 0x409D
#define VAR_TH_MISTY_GIFT 0x40A1
#define VAR_TH_SHINY_RATE 0x40A8
#define VAR_TH_CLOCK_MODE 0x40B8
#define VAR_TH_CLOCK_REAL_LO 0x40BB
#define VAR_TH_CLOCK_REAL_HI 0x40DB
#define VAR_TH_CLOCK_DISPLAY_LO 0x40DC
#define VAR_TH_CLOCK_DISPLAY_HI 0x40E5
// Visual time is 0..86399 (17 bits). The unused upper 15 bits identify
// initialized Playtest 9 state without taking another persistent variable.
#define TH_STATE_VERSION_MASK 0xFFFE
#define TH_STATE_VERSION_9 0xA902
#define TH_STATE_VERSION_10 0xA904
#define FLAG_TH_LAB_INTRO FLAG_UNUSED_0x04E
#define FLAG_TH_DIG_TM FLAG_UNUSED_0x04F
#define FLAG_TH_MAGIKARP FLAG_UNUSED_0x022
#define FLAG_TH_MISTY_TM FLAG_UNUSED_0x023
#define FLAG_TH_CHAPTER_COMPLETE FLAG_UNUSED_0x024
#define FLAG_TH_CLOCK_ANCHORED FLAG_UNUSED_0x025
#define FLAG_TH_ROUTE22_RIVAL FLAG_UNUSED_0x026
#define FLAG_TH_BRIDGE_RIVAL FLAG_UNUSED_0x027
#define FLAG_TH_FOSSIL FLAG_UNUSED_0x028

#define TH_OUTFIT_RED          0
#define TH_OUTFIT_LEAF         1
#define TH_OUTFIT_BRENDAN      2
#define TH_OUTFIT_MAY          3
#define TH_OUTFIT_GOLD         4
#define TH_OUTFIT_KRIS         5
#define TH_OUTFIT_SILVER       6
#define TH_OUTFIT_COUNT        7
#define TH_STAGE_HOME          0
#define TH_STAGE_INVITED       1
#define TH_STAGE_PARTNER       2
#define TH_STAGE_BATTLE_DONE   3
#define TH_STAGE_COMPLETE      4
#define TH_SUPPLY_BALLS        1
#define TH_SUPPLY_POTIONS      2
#define TH_SUPPLY_DEX          4
#define TH_SUPPLIES_COMPLETE   7
#define FLAG_TH_BROCK_TM FLAG_UNUSED_0x020
#define FLAG_TH_HIDE_ROBIN_TOWN FLAG_TEMP_1
#define FLAG_TH_HIDE_ROBIN_LAB  FLAG_TEMP_2
#define FLAG_TH_HIDE_CHAPTER_RIVAL FLAG_TEMP_4

#define FLAG_TH_PICKUP_0 FLAG_UNUSED_0x029
#define FLAG_TH_PICKUP_1 FLAG_UNUSED_0x02A
#define FLAG_TH_PICKUP_2 FLAG_UNUSED_0x02B
#define FLAG_TH_PICKUP_3 FLAG_UNUSED_0x02C
#define FLAG_TH_PICKUP_4 FLAG_UNUSED_0x02D
#define FLAG_TH_PICKUP_5 FLAG_UNUSED_0x02E
#define FLAG_TH_PICKUP_6 FLAG_UNUSED_0x02F
#define FLAG_TH_PICKUP_7 FLAG_UNUSED_0x030
#define FLAG_TH_PICKUP_8 FLAG_UNUSED_0x031
#define FLAG_TH_PICKUP_9 FLAG_UNUSED_0x032
#define FLAG_TH_PICKUP_10 FLAG_UNUSED_0x033
#define FLAG_TH_PICKUP_11 FLAG_UNUSED_0x034
#define FLAG_TH_PICKUP_12 FLAG_UNUSED_0x035
#define FLAG_TH_PICKUP_13 FLAG_UNUSED_0x036
#define FLAG_TH_PICKUP_14 FLAG_UNUSED_0x037
#define FLAG_TH_PICKUP_15 FLAG_UNUSED_0x038
#define FLAG_TH_PICKUP_16 FLAG_UNUSED_0x039
#define FLAG_TH_PICKUP_17 FLAG_UNUSED_0x03A
#define FLAG_TH_PICKUP_18 FLAG_UNUSED_0x03B
#define FLAG_TH_PICKUP_19 FLAG_UNUSED_0x03C
#define FLAG_TH_PICKUP_20 FLAG_UNUSED_0x03D
#define FLAG_TH_PICKUP_21 FLAG_UNUSED_0x03E
#define FLAG_TH_PICKUP_22 FLAG_UNUSED_0x03F
#define FLAG_TH_PICKUP_23 FLAG_UNUSED_0x040
#define FLAG_TH_PICKUP_24 FLAG_UNUSED_0x041
#define FLAG_TH_PICKUP_25 FLAG_UNUSED_0x042
#define FLAG_TH_PICKUP_26 FLAG_UNUSED_0x043
#define FLAG_TH_PICKUP_27 FLAG_UNUSED_0x044
#define FLAG_TH_PICKUP_28 FLAG_UNUSED_0x045
#define FLAG_TH_PICKUP_29 FLAG_UNUSED_0x046
#define FLAG_TH_PICKUP_30 FLAG_UNUSED_0x047
#define FLAG_TH_PICKUP_31 FLAG_UNUSED_0x048
#define FLAG_TH_PICKUP_32 FLAG_UNUSED_0x049
#define FLAG_TH_FOSSIL_DOME FLAG_UNUSED_0x04A
#define FLAG_TH_FOSSIL_HELIX FLAG_UNUSED_0x04B
#define FLAG_TH_SEEN_FOREST FLAG_UNUSED_0x04C
#define FLAG_TH_SEEN_MT_MOON FLAG_UNUSED_0x04D
#endif
