"""Reconstruct ROM-side research crops from native map metatiles, never frames."""
from pathlib import Path
import argparse, hashlib, json, re, struct
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
# Stable photo ID order. Crops are in authored map tile coordinates.
SCENES = [
    ('hoothoot', 'TH_Route1', 10, 14),
    ('treecko', 'TH_ViridianForest', 21, 49),
    ('shroomish', 'TH_ViridianForest', 2, 38),
    ('mt_moon', 'TH_MtMoonB2F', 19, 27),
    ('harbor', 'TH12_VermilionCity', 22, 26),
    ('forest_pair', 'TH_ViridianForest', 24, 29),
    ('diglett_cave', 'TH13_DiglettsCave_B1F', 69, 65),
    ('route9', 'TH13_Route9', 5, 1),
    ('rock_tunnel', 'TH13_RockTunnel_1F', 16, 1),
    ('lavender', 'TH13_LavenderTown', 10, 3),
]

def tileset_root(label):
    text = (ROOT/'src/data/tilesets/three_horizons.h').read_text()
    record = re.search(r'const struct Tileset '+re.escape(label)+r'\s*=\s*\{(.*?)\};', text, re.S).group(1)
    meta_label = re.search(r'\.metatiles = (\w+)', record).group(1)
    path = re.search(r'const u16 '+re.escape(meta_label)+r'\[\] = INCBIN_U16\("(.*?)"\)', text).group(1)
    return (ROOT/path).parent

def render_scene(map_name, left, top):
    mapping = json.loads((ROOT/'data/maps'/map_name/'map.json').read_text())
    layouts = json.loads((ROOT/'data/layouts/layouts.json').read_text())['layouts']
    layout = next(l for l in layouts if l['id'] == mapping['layout'])
    assert 0 <= left <= layout['width']-14 and 0 <= top <= layout['height']-6
    roots = [tileset_root(layout[k]) for k in ('primary_tileset','secondary_tileset')]
    images = [Image.open(r/'tiles.png') for r in roots]
    metatiles = [(r/'metatiles.bin').read_bytes() for r in roots]
    palettes = [[tuple(map(int,s.split())) for s in (roots[int(i>=7)]/'palettes'/f'{i:02}.pal').read_text().splitlines()[3:19]] for i in range(16)]
    raw = (ROOT/layout['blockdata_filepath']).read_bytes()
    grid = struct.unpack('<'+str(len(raw)//2)+'H', raw)
    result = Image.new('RGB',(224,96))
    for by in range(6):
        for bx in range(14):
            block = grid[(top+by)*layout['width']+left+bx] & 1023
            secondary = int(block>=640)
            for layer, tile in enumerate(struct.unpack_from('<8H',metatiles[secondary],(block-640*secondary)*16)):
                index = tile & 1023; secondary_tile = int(index>=640); index -= 640*secondary_tile
                sheet = images[secondary_tile]; columns = sheet.width//8
                for y in range(8):
                    for x in range(8):
                        sx = 7-x if tile&0x400 else x; sy = 7-y if tile&0x800 else y
                        color = sheet.getpixel((index%columns*8+sx,index//columns*8+sy))
                        if layer<4 or color:
                            result.putpixel((bx*16+layer%2*8+x,by*16+(layer%4)//2*8+y),palettes[tile>>12][color])
    return result, layout

def encode(image):
    # Reserve transparent index zero. Each photo owns one BG palette bank;
    # fifteen opaque map colors leave all native subject OBJ palettes intact.
    indexed = image.quantize(colors=15, method=Image.Quantize.MEDIANCUT, dither=Image.Dither.NONE)
    colors = indexed.getpalette()[:45]
    colors += [0]*(45-len(colors))
    palette = bytes(2)+b''.join(struct.pack('<H', (colors[i]>>3)|((colors[i+1]>>3)<<5)|((colors[i+2]>>3)<<10)) for i in range(0,45,3))
    pixels = indexed.load(); tiles = bytearray()
    for ty in range(12):
        for tx in range(28):
            for y in range(8):
                for x in range(0,8,2): tiles.append((pixels[tx*8+x,ty*8+y]+1)|((pixels[tx*8+x+1,ty*8+y]+1)<<4))
    assert len(tiles)==10752 and len(palette)==32
    return bytes(tiles), palette, indexed.convert('RGB')

def generate(destination):
    destination.mkdir(parents=True,exist_ok=True)
    manifest = []
    for photo_id,(name,map_name,left,top) in enumerate(SCENES):
        image,layout = render_scene(map_name,left,top)
        tiles,palette,preview = encode(image)
        for ext,data in [('4bpp',tiles),('gbapal',palette)]: (destination/(name+'.'+ext)).write_bytes(data)
        preview.save(destination/(name+'.png'))
        manifest.append(dict(id=photo_id,name=name,map=map_name,left=left,top=top,width=224,height=96,source_layout=layout['blockdata_filepath'],source_sha256=hashlib.sha256((ROOT/layout['blockdata_filepath']).read_bytes()).hexdigest(),tiles_sha256=hashlib.sha256(tiles).hexdigest(),palette_sha256=hashlib.sha256(palette).hexdigest()))
    (destination/'manifest.json').write_text(json.dumps(manifest,indent=2)+'\n')
    header = ['// Generated by tools/three_horizons/research_photo_art.py.',
              '// ROM-authored map crops; no framebuffer or saved-image storage.',
              'struct THResearchBackdropArt { const void *tiles; const u16 *palette; };']
    for name, *_ in SCENES:
        prefix = f'graphics/three_horizons/research/photos/{name}'
        header += [f'static const u32 sPhoto_{name}_Tiles[] = INCBIN_U32("{prefix}.4bpp");',
                   f'static const u16 sPhoto_{name}_Palette[] = INCBIN_U16("{prefix}.gbapal");']
    header += ['static const struct THResearchBackdropArt sResearchBackdropArt[TH_RESEARCH_PHOTO_COUNT] = {']
    header += [f'    {{sPhoto_{name}_Tiles, sPhoto_{name}_Palette}},' for name,*_ in SCENES]
    header += ['};','STATIC_ASSERT(ARRAY_COUNT(sResearchBackdropArt) == TH_RESEARCH_PHOTO_COUNT, ResearchBackdropCountMatchesPhotos);']
    (ROOT/'src/data/three_horizons_research_photos.h').write_text('\n'.join(header)+'\n')
    return manifest

if __name__ == '__main__':
    parser = argparse.ArgumentParser(); parser.add_argument('--output',type=Path,default=ROOT/'graphics/three_horizons/research/photos')
    args = parser.parse_args(); print(json.dumps(generate(args.output),indent=2))
