"""Exercise mapjson output and the closed demo map graph (stdlib only)."""
import json
import hashlib
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import unittest

ROOT = Path(__file__).resolve().parents[3]
EXE = ROOT / 'tools/mapjson' / ('mapjson.exe' if os.name == 'nt' else 'mapjson')
NAMES = tuple(json.loads((ROOT / 'tools/mapjson/three_horizons_maps.json').read_text())['maps'])


class MapContract(unittest.TestCase):
    def test_individual_project_maps_generate_in_every_build_mode(self):
        # Make prepares every map's events before linking only selected groups.
        constants = ROOT / 'include/constants/map_groups.h'
        before = constants.read_bytes() if constants.exists() else None
        try:
            for version in ('emerald', 'firered', 'three_horizons'):
                constants.write_text(self.generate('groups', version)['map_groups.h'])
                for name in NAMES:
                    with tempfile.TemporaryDirectory(dir=ROOT, prefix='.th-') as folder:
                        run = subprocess.run([str(EXE), 'map', version,
                            f'data/maps/{name}/map.json', 'data/layouts/layouts.json', folder],
                            cwd=ROOT, capture_output=True, text=True)
                        self.assertEqual(run.returncode, 0, (version, name, run.stderr))
                        self.assertIn(name, (Path(folder) / 'header.inc').read_text())
        finally:
            if before is None:
                constants.unlink(missing_ok=True)
            else:
                constants.write_bytes(before)

    def generate(self, mode, version, response=False, normalize_output_paths=False):
        with tempfile.TemporaryDirectory(dir=ROOT, prefix='.th-') as folder:
            out = Path(folder)
            args = [str(EXE), mode, version]
            if mode == 'layouts':
                args += ['data/layouts/layouts.json']
            else:
                args += ['data/maps/map_groups.json']
                map_paths = []
                for i, path in enumerate(sorted((ROOT / 'data/maps').glob('*/map.json'))):
                    short = out / str(i)
                    short.write_bytes(path.read_bytes())
                    map_paths.append(str(short.relative_to(ROOT)))
                if response:
                    listing = out / 'map paths.txt'
                    listing.write_text('\n'.join(map_paths) + '\n')
                    args.append('@' + str(listing.relative_to(ROOT)))
                else:
                    args += map_paths
            args += [str(out), str(out)]
            run = subprocess.run(args, cwd=ROOT, capture_output=True, text=True)
            self.assertEqual(run.returncode, 0, run.stderr)
            generated = {p.name: p.read_text() for p in out.iterdir() if p.suffix in ('.h', '.inc')}
            if normalize_output_paths:
                # groups.inc embeds the unique temporary directory name.
                # Normalize that component (also after MSYS path conversion),
                # retaining the rest of every path and generated byte.
                generated = {name: contents.replace(out.name, '<GENERATED>')
                             for name, contents in generated.items()}
            return generated

    def test_response_file_preserves_all_map_groups_beyond_windows_command_limit(self):
        # The normal build's full map-name command exceeds Windows' limit.
        # Short controlled paths let the old direct mode be our oracle.
        for version in ('emerald', 'firered', 'three_horizons'):
            self.assertEqual(self.generate('groups', version, response=True, normalize_output_paths=True),
                             self.generate('groups', version, normalize_output_paths=True))

    def test_event_constants_accept_separator_free_response_file_with_checked_strings(self):
        # A plain @.mapjson-inputs has no directory separator. Checked libstdc++
        # makes an accidental filename[npos] read fail deterministically.
        compiler = shutil.which('g++')
        self.assertIsNotNone(compiler, 'g++ is required for checked mapjson regression')
        with tempfile.TemporaryDirectory(dir=ROOT, prefix='.th-') as folder:
            out = Path(folder)
            checked = out / 'mapjson-checked.exe'
            build = subprocess.run([compiler, '-std=c++17', '-O1', '-D_GLIBCXX_ASSERTIONS',
                str(ROOT/'tools/mapjson/json11.cpp'), str(ROOT/'tools/mapjson/mapjson.cpp'),
                '-o', str(checked)], capture_output=True, text=True)
            self.assertEqual(build.returncode, 0, build.stderr)
            fixtures = {
                'tools/mapjson/three_horizons_maps.json': {'maps': ['TH_Probe']},
                'data/layouts/layouts.json': {'layouts': [{'id': 'LAYOUT_TH_PROBE'}]},
                'data/maps/TH_Probe/map.json': {'id': 'MAP_TH_PROBE', 'name': 'TH_Probe',
                    'layout': 'LAYOUT_TH_PROBE', 'object_events': [{'local_id': 'LOCALID_PROBE'}],
                    'warp_events': [{'warp_id': 'WARP_PROBE'}]},
            }
            for name, data in fixtures.items():
                path = out / name
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(json.dumps(data))
            map_path = 'data/maps/TH_Probe/map.json'
            (out/'.mapjson-inputs').write_text(map_path + '\n')
            for version in ('emerald', 'firered', 'three_horizons'):
                results = []
                for argument in (map_path, '@.mapjson-inputs'):
                    generated = out / 'ids.h'
                    run = subprocess.run([str(checked), 'event_constants', version,
                        argument, str(generated)], cwd=out, capture_output=True, text=True)
                    self.assertEqual(run.returncode, 0, (version, argument, run.stderr))
                    results.append(generated.read_text())
                self.assertEqual(results[0], results[1])
                self.assertIn('#define LOCALID_PROBE 1', results[0])
                self.assertIn('#define WARP_PROBE 0', results[0])

    def test_windows_response_list_tracks_removed_maps_without_rewriting_unchanged_lists(self):
        make = shutil.which('make')
        self.assertIsNotNone(make, 'GNU make is required to verify the actual response-file rule')
        with tempfile.TemporaryDirectory(dir=ROOT, prefix='.th-') as folder:
            out = Path(folder)
            for name in ('First', 'Removed'):
                path = out / 'data/maps' / name / 'map.json'
                path.parent.mkdir(parents=True)
                path.write_text('{}')
            def generate_list():
                run = subprocess.run([make, '-f', str(ROOT / 'map_data_rules.mk'),
                    '.mapjson-inputs', 'OS=Windows_NT', 'DATA_ASM_SUBDIR=data',
                    'DATA_SRC_SUBDIR=src/data', 'DATA_ASM_BUILDDIR=build'],
                    cwd=out, capture_output=True, text=True)
                self.assertEqual(run.returncode, 0, run.stderr)
            generate_list()
            listing = out / '.mapjson-inputs'
            self.assertEqual(listing.read_text().splitlines(),
                             ['data/maps/First/map.json', 'data/maps/Removed/map.json'])
            stamp = listing.stat().st_mtime_ns
            generate_list()
            self.assertEqual(listing.stat().st_mtime_ns, stamp)
            (out / 'data/maps/Removed/map.json').unlink()
            generate_list()
            self.assertEqual(listing.read_text().splitlines(), ['data/maps/First/map.json'])

    def test_demo_includes_native_kanto_layouts(self):
        """Rejects a mode that omits the bedroom or emits its Emerald format."""
        out = self.generate('layouts', 'three_horizons')
        self.assertIn('PalletTown_PlayersHouse_2F_FRLG_Layout::', out['layouts.inc'])
        self.assertRegex(out['layouts.inc'], r'PalletTown_PlayersHouse_2F_FRLG_Layout::[\s\S]*?\.byte TRUE')

    def test_demo_group_is_selected_only_for_demo(self):
        for version in ('emerald', 'firered', 'three_horizons'):
            out = self.generate('groups', version)
            for name in NAMES:
                line = '\t.4byte ' + name + '\n'
                self.assertEqual(line in out['groups.inc'], version == 'three_horizons', (name, version))

    def test_demo_maps_form_closed_graph(self):
        maps = {}
        for name in NAMES:
            path = ROOT / 'data/maps' / name / 'map.json'
            self.assertTrue(path.exists(), f'Missing demo map: {name}')
            record = json.loads(path.read_text())
            maps[record['id']] = record
            for obj in record['object_events']:
                if obj.get('local_id'):
                    self.assertRegex(obj['local_id'], r'^[A-Za-z_][A-Za-z_0-9]*$')
        layouts = {x.get('id'): x for x in json.loads((ROOT / 'data/layouts/layouts.json').read_text())['layouts']}
        for record in maps.values():
            layout = layouts[record['layout']]
            for kind in ('object_events', 'warp_events', 'coord_events', 'bg_events'):
                for event in record[kind]:
                    self.assertGreaterEqual(event['x'], 0)
                    self.assertGreaterEqual(event['y'], 0)
                    self.assertLess(event['x'], layout['width'])
                    self.assertLess(event['y'], layout['height'])
            for warp in record['warp_events']:
                self.assertIn(warp['dest_map'], maps)
                self.assertGreaterEqual(int(warp['dest_warp_id']), 0)
                self.assertLess(int(warp['dest_warp_id']), len(maps[warp['dest_map']]['warp_events']))
            for connection in record['connections'] or []:
                self.assertIn(connection['map'], maps)

    def test_generation_does_not_mutate_healing_source(self):
        path = ROOT / 'src/data/heal_locations.json'
        before = path.read_bytes()
        for version in ('emerald', 'firered', 'three_horizons'):
            self.generate('groups', version)
            self.assertEqual(before, path.read_bytes())

    def test_original_map_indices_and_layout_tables_are_preserved(self):
        fixture = json.loads(Path(__file__).with_name('original-map-indices.json').read_text())
        for version, expected in fixture.items():
            layouts = self.generate('layouts', version)['layouts_table.inc']
            self.assertEqual(hashlib.sha256(layouts.encode()).hexdigest(), expected['layouts_sha256'])
            constants = self.generate('groups', version)['map_groups.h']
            indices = '\n'.join(line for line in constants.splitlines()
                                if re.match(r'\s*MAP_\w+\s*=', line) and not any(prefix in line for prefix in ('MAP_TH_', 'MAP_TH12_', 'MAP_TH13_')))
            self.assertEqual(hashlib.sha256(indices.encode()).hexdigest(), expected['map_indices_sha256'])

    def test_project_manifest_rejects_missing_map(self):
        path = ROOT / 'tools/mapjson/three_horizons_maps.json'
        original = path.read_bytes()
        try:
            path.write_text(json.dumps({'maps': ['TH_Missing']}))
            with tempfile.TemporaryDirectory() as out:
                run = subprocess.run([str(EXE), 'layouts', 'three_horizons',
                                      'data/layouts/layouts.json', out, out],
                                     cwd=ROOT, capture_output=True, text=True)
            self.assertNotEqual(run.returncode, 0)
            self.assertIn('TH_Missing', run.stderr)
        finally:
            path.write_bytes(original)

    def test_windows_line_endings_are_read_without_trailing_nuls(self):
        path = ROOT / 'tools/mapjson/three_horizons_maps.json'
        original = path.read_bytes()
        try:
            path.write_bytes(original.replace(b'\r\n', b'\n').replace(b'\n', b'\r\n'))
            self.generate('layouts', 'three_horizons')
        finally:
            path.write_bytes(original)


if __name__ == '__main__':
    unittest.main()
