// Generated by tools/three_horizons/research_photo_art.py.
// ROM-authored map crops; no framebuffer or saved-image storage.
struct THResearchBackdropArt { const void *tiles; const u16 *palette; };
static const u32 sPhoto_hoothoot_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/hoothoot.4bpp");
static const u16 sPhoto_hoothoot_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/hoothoot.gbapal");
static const u32 sPhoto_treecko_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/treecko.4bpp");
static const u16 sPhoto_treecko_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/treecko.gbapal");
static const u32 sPhoto_shroomish_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/shroomish.4bpp");
static const u16 sPhoto_shroomish_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/shroomish.gbapal");
static const u32 sPhoto_mt_moon_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/mt_moon.4bpp");
static const u16 sPhoto_mt_moon_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/mt_moon.gbapal");
static const u32 sPhoto_harbor_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/harbor.4bpp");
static const u16 sPhoto_harbor_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/harbor.gbapal");
static const u32 sPhoto_forest_pair_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/forest_pair.4bpp");
static const u16 sPhoto_forest_pair_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/forest_pair.gbapal");
static const u32 sPhoto_diglett_cave_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/diglett_cave.4bpp");
static const u16 sPhoto_diglett_cave_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/diglett_cave.gbapal");
static const u32 sPhoto_route9_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/route9.4bpp");
static const u16 sPhoto_route9_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/route9.gbapal");
static const u32 sPhoto_rock_tunnel_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/rock_tunnel.4bpp");
static const u16 sPhoto_rock_tunnel_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/rock_tunnel.gbapal");
static const u32 sPhoto_lavender_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/lavender.4bpp");
static const u16 sPhoto_lavender_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/lavender.gbapal");
static const u32 sPhoto_mothers_watch_Tiles[] = INCBIN_U32("graphics/three_horizons/research/photos/mothers_watch.4bpp");
static const u16 sPhoto_mothers_watch_Palette[] = INCBIN_U16("graphics/three_horizons/research/photos/mothers_watch.gbapal");
static const struct THResearchBackdropArt sResearchBackdropArt[TH_RESEARCH_PHOTO_COUNT] = {
    {sPhoto_hoothoot_Tiles, sPhoto_hoothoot_Palette},
    {sPhoto_treecko_Tiles, sPhoto_treecko_Palette},
    {sPhoto_shroomish_Tiles, sPhoto_shroomish_Palette},
    {sPhoto_mt_moon_Tiles, sPhoto_mt_moon_Palette},
    {sPhoto_harbor_Tiles, sPhoto_harbor_Palette},
    {sPhoto_forest_pair_Tiles, sPhoto_forest_pair_Palette},
    {sPhoto_diglett_cave_Tiles, sPhoto_diglett_cave_Palette},
    {sPhoto_route9_Tiles, sPhoto_route9_Palette},
    {sPhoto_rock_tunnel_Tiles, sPhoto_rock_tunnel_Palette},
    {sPhoto_lavender_Tiles, sPhoto_lavender_Palette},
    {sPhoto_mothers_watch_Tiles, sPhoto_mothers_watch_Palette},
};
STATIC_ASSERT(ARRAY_COUNT(sResearchBackdropArt) == TH_RESEARCH_PHOTO_COUNT, ResearchBackdropCountMatchesPhotos);
